slient install

diff --git a/init/dev/dev-arch b/init/dev/dev-arch
--- a/init/dev/dev-arch
+++ b/init/dev/dev-arch
@@ -11,14 +11,17 @@ basicApps="neovim vim git openssh net-tools tree screenfetch wget cronie unzip z
 devApps="base-devel linux-headers clang cmake python boost python-pip go go-tools"
 
 read -p "Install development apps (ie:clang python boost go) [Y/n] " -t 3 installDev
-pacman -Syu --noconfirm --needed
+echo "pacman -Syu ..."
+pacman -Syu --noconfirm --needed >/dev/null 2>&1 || { echo "pacman upate failed!";exit 1; }
 for app in ${basicApps};do
-    pacman -S $app --noconfirm --needed
+    echo "Install $app..."
+    pacman -S $app --noconfirm --needed >/dev/null 2>&1
 done
 
 if [[ "$installDev" != [nN] ]];then
     for app in ${devApps};do
-        pacman -S $app --noconfirm --needed
+        echo "Install $app..."
+        pacman -S $app --noconfirm --needed >/dev/null 2>&1
     done
 fi
 
diff --git a/init/dev/dev-debian b/init/dev/dev-debian
--- a/init/dev/dev-debian
+++ b/init/dev/dev-debian
@@ -18,9 +18,10 @@ fi
 basicApps="sudo vim vim-gtk tree curl screenfetch zsh openssh-server nload"
 devApps="build-essential cmake clang  python-apt python-dev python-pip python3-dev python3-pip libboost-all-dev golang golang-golang-x-tools ncurses-dev"
 
-$installer update -y
-read -p "Install development tools (ie:clang python boost golang)? [y/N] " -t 3 installDev
-read -p "Setup swap? [Y/n]" -t 3 setupSwap
+echo "apt update..."
+$installer update -y >/dev/null 2>&1 || { echo "apt update failed!"; exit 1; }
+read -p "Install development tools (ie:clang python boost golang)? [y/N] "  installDev
+read -p "Setup swap? [Y/n]"  setupSwap
 # read -p "Whom to be add to sudo group?" -t 3 sudoer
 
 # #TODO check $sudoer existence. if $sudoer does not exist?
@@ -29,12 +30,14 @@ read -p "Setup swap? [Y/n]" -t 3 setupSwap
 # fi
 
 for app in ${basicApps};do
-    $installer install $app -y
+    echo "Install $app..."
+    $installer install $app -y >/dev/null 2>&1 || { echo "Install $app failed."; }
 done
 
 if [[ "$installDev" == [yY] ]];then
     for app in ${devApps};do
-        $installer install $app -y
+        echo "Install $app..."
+        $installer install $app -y >/dev/null 2>&1 || { echo "Install $app failed."; }
     done
 fi
 
diff --git a/init/dev/dev-ubuntu b/init/dev/dev-ubuntu
--- a/init/dev/dev-ubuntu
+++ b/init/dev/dev-ubuntu
@@ -27,16 +27,19 @@ basicApps="vim vim-gtk tree curl screenfetch zsh"
 devApps="linux-headers-generic build-essential cmake clang  python-apt python-dev python-pip python3-dev python3-pip libboost-all-dev golang golang-golang-x-tools ncurses-dev"
 inputApps="fcitx fcitx-sunpinyin fcitx-table-wubi"
 
-$installer update -y
+echo "apt update..."
+$installer update -y >/dev/null 2>&1 || { echo "apt update failed."; exit 1; }
 read -p "Install development tools (ie:clang python golang)? [Y/n] " -t 3 installDev
 read -p "Install fcitx input method? [y/N] " -t 3 installFcitx
 for app in ${basicApps};do
-    $installer install $app -y
+    echo "Install $app..."
+    $installer install $app -y >/dev/null 2>&1 || { echo "Install $app failed."; }
 done
 
 if [[ "$installDev" != [nN] ]];then
     for app in ${devApps};do
-        $installer install $app -y
+        echo "Install $app..."
+        $installer install $app -y >/dev/null 2>&1 || { echo "Install $app failed."; }
     done
 fi
 
